version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: unless-stopped
    container_name: Fichajes-nginx
    ports:
      - 8002:80
    volumes:
      - ./src/laravel:/var/www/html
      - ./src/react/build:/var/www/html/react
      - ./.env.example:/var/www/html/.env
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - redis
    networks:
      - laravel

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: Fichajes-php
    ports:
      - "9002:9000"
    volumes:
      - ./src/laravel:/var/www/html
      - ./.env.example:/var/www/html/.env
    networks:
      - laravel

  mysql:
    image: mariadb:10.6
    container_name: Fichajes-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: bibiano
      MYSQL_PASSWORD: bibiano

      MYSQL_ROOT_PASSWORD: bibiano2023
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: Fichajes-redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: Fichajes-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: bibiano
      MYSQL_ROOT_PASSWORD: bibiano2023
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    ports:
      - 8888:80
    networks:
      - laravel

  laravel-migrate-seed:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: Fichajes-laravel-migrate-seed
    volumes:
      - ./src/laravel:/var/www/html
      - ./.env.example:/var/www/html/.env
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        php artisan migrate
        php artisan db:seed DatabaseSeeder
    networks:
      - laravel

  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: Fichajes--composer
    volumes:
      - ./src/laravel:/var/www/html
      - ./.env.example:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-laravel} #system user
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - laravel

  artisan:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: Fichajes-artisan
    volumes:
      - ./src/laravel:/var/www/html
      - ./.env.example:/var/www/html/.env
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel

  npm:
    image: node:alpine
    container_name: Fichajes-npm
    volumes:
      - ./src/react:/var/www/html
    ports:
      - "3010:3000"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel
